# Generated by Django 4.2.20 on 2025-06-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_community_communitypost_communitymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='member_limit',
            field=models.IntegerField(default=5),
        ),
    ]
